// at the top of your component file

import { fetchEntries } from "../util/contentfulQuery";

//

import Head from "next/head";

export default function Home({ posts }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}
